dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
script: mvn install
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/Multiverse-Core-4.1.0-SNAPSHOT.jar"
  on:
    tags: true
